version: "3"

services:
  app:
    command: >
      sh -c "
          sleep 10 &&
          python3 manage.py migrate &&
          python3 manage.py createsuperuser --noinput &&
          python3 manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  streamlit:
    restart: always
    image: python:3.10.2
    command: sh -c "pip install streamlit requests && 
                streamlit run --server.port 8501 /app/app.py"
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    depends_on:
      - app
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "5433:5432"


volumes:
  postgres_data:
