# Generated by Django 5.0.4 on 2024-06-08 14:01

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='file',
            field=models.FileField(null=True, storage=storages.backends.s3.S3Storage(), upload_to='lessons_files/'),
        ),
    ]
