# Generated by Django 5.0.4 on 2024-06-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_lessoncontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='file',
            field=models.FileField(null=True, upload_to='lessons_files/'),
        ),
    ]
