# Generated by Django 5.0.4 on 2024-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_lessoncontent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons_files/'),
        ),
    ]
