# Generated by Django 5.0.4 on 2024-06-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_lessoncontent_name_alter_lessoncontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
