# Generated by Django 5.0.4 on 2024-06-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_lessoncontent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseimage',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='courseimage',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
